abstract: Dump big dumb Perl structs to anonymous JavaScript structs
author: 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Data-JavaScript-Anon
no_index:
  directory:
    - inc
    - t
requires:
  Params::Util: 0.10
  perl: 5.005
version: 1.00
