name: Data-JavaScript-Anon
version: 0.6
abstract: Dump big dumb Perl structs to anonymous JavaScript structs
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
