---
abstract: 'Dump big dumb Perl structs to anonymous JavaScript structs'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.82
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::JavaScript::Anon
name: Data-JavaScript-Anon
no_index:
  directory:
    - inc
    - t
requires:
  Class::Default: 1.51
  Params::Util: 0.10
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Data-JavaScript-Anon
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Data-JavaScript-Anon
version: 1.03
